Fix for crash seen when wxToolBarBase destructor is invoked.
wxWidgets/wxWidgets pull request #1140
Opened 2019-01-14 16:20 UTC by liamtreacy

`wxToolBarBase::~wxToolBarBase()` calls `frame->SetToolBar(NULL);` which results in a crash due to the existing implementation. I've changed the behaviour to avoid the crash, maintain existing functionality and it matches the behaviour seen in GTK.

2019-01-14 21:46 UTC, vadz requested changes
What exactly is the crash due to? The current code does look suspicious, but the new version is not right neither, so I'd like to understand which problem exactly are we fixing. TIA!

2019-01-14 21:46 UTC, vadz commented on src/qt/frame.cpp
> +            GetQMainWindow()->removeToolBar(m_frameToolBar->GetQToolBar());
Sorry, this doesn't seem right. We shouldn't call `removeToolBar()` if the new toolbar is non-null.

2019-01-15 20:58 UTC, vadz commented
Sorry, no, this still looks wrong. Now the toolbar won't be removed if you had one previously and call `SetToolBar(NULL)` later as the condition `m_frameToolBar != NULL` will be false. Granted, it looks like this problem also exists in wxGTK, but it's still wrong... In fact, the code in the `else if` block is now _never_ executed, which just can't be right.

Finally, note that storing the pointer in `m_frameToolBar` is definitely the right thing to do, but this is already done by the base class version, which is called from here. So I have no idea how can `m_frameToolBar` become invalid/dangling. If you don't see it neither, could you perhaps compile with ASAN and see if it detects the problem?

2019-01-18 13:56 UTC, vadz commented
I'm sorry, I still don't understand. How can Qt-specific `GetQToolBar()` be called from the base `wxToolBarBase`? This seems to be impossible, virtual or not...

I do agree that this method shouldn't be virtual and I can apply this PR, but I just don't see how can it fix anything.

2019-01-18 15:22 UTC, liamtreacy commented
I understand your difficulty with it, I'm finding it quite hard myself! 

The problem is the structure of the code, namely wxToolbarBase having a wxFrame which itself has a wxToolbar. Perhaps the following demo code will show how such a crash can happen better than I can (thanks to @evileye-uk ) - https://ideone.com/HUYE2U

If you set the close() method in that demo to be virtual, it will crash. Non-virtual and no crash.

2019-01-19 11:37 UTC, evileye-uk commented
Unfortunately, the non-virtual close (which doesn't crash now) could do *anything* it wants. Leaving the code like this is leaving a trap for later. I think the dependencies/structure needs to change, rather than taking this PR as a fix.

2019-01-20 02:21 UTC, closed without merging