Qt dropdown
wxWidgets/wxWidgets pull request #1143
Opened 2019-01-18 11:10 UTC by evileye-uk

In wxQt, wxComboBox and wxChoice were both failing tests for value, text events, selection, insertion point. The sorting was working, but not in lexical order. There was no test for WriteText(), which was also not working in wxComboBox. This attempts to address those issues.

2019-01-19 22:00 UTC, vadz reviewed
Looks good, but it would be great if you could please fix the few minor cosmetic comments here and there (I ran out of patience with all the `if(`s, please insert the missing spaces even where I didn't leave suggestions for doing it).

TIA!

2019-01-20 10:19 UTC, evileye-uk commented on include/wx/qt/choice.h
> +    virtual void InitialiseSort(QComboBox *combo);
Agreed. Should never have been virtual. Fixed name.

2019-01-20 10:20 UTC, evileye-uk commented on src/qt/combobox.cpp
> +        Ignore( QComboBox *combo ) :
Missed this, thanks.

2019-01-20 10:35 UTC, evileye-uk commented on src/qt/combobox.cpp
> +    wxString front = original.SubString( 0, from - 1 ) + value;
Added change to keep negative "to" working, but otherwise, as you requested.

2019-01-20 10:37 UTC, evileye-uk commented on src/qt/combobox.cpp
> +            handler( dynamic_cast<wxQtComboBox*>(combo) )
I have not fixed this yet. The base class and the derived class differ.

2019-01-20 10:40 UTC, evileye-uk commented
Current push deals with everything except the dynamic_cast.

2019-01-20 17:37 UTC, catalinr requested changes
Suggestions for whitespace changes based on the Coding Guidelines.
They are not all the required changes, only a few that should give a relevant idea.

2019-01-20 17:37 UTC, catalinr commented on src/qt/choice.cpp
> +            bool lessThan( const QModelIndex &left, const QModelIndex &right ) const wxOVERRIDE
As part of the [Coding Guidelines](https://www.wxwidgets.org/develop/coding-guidelines/), pretty much the use of all spaces is well defined. People don't read them or at least they are not followed, and are seldomly enforced, but is it too big of a burden to at least try to follow them in new code?
i.e.
```suggestion
            bool lessThan(const QModelIndex& left, const QModelIndex& right) const wxOVERRIDE
```
as very nicely exemplified [here](https://www.wxwidgets.org/develop/coding-guidelines/#no_overloaded_virtuals).

2019-01-20 17:37 UTC, catalinr commented on src/qt/choice.cpp
> +                const QVariant leftData = sourceModel()->data( left );
```suggestion
                const QVariant leftData = sourceModel()->data(left);
```
or even better?
```suggestion
                const QVariant& leftData = sourceModel()->data(left);
```

2019-01-20 17:37 UTC, catalinr commented on src/qt/choice.cpp
> +                if ( insensitiveResult == 0 )
```suggestion
                if ( !insensitiveResult )
```
...but the name might actually be confusing now...

2019-01-20 17:37 UTC, catalinr commented on src/qt/choice.cpp
> +    class wxQtChoice : public wxQtEventSignalHandler< QComboBox, wxChoice >
```suggestion
    class wxQtChoice : public wxQtEventSignalHandler<QComboBox, wxChoice>
```

2019-01-20 17:37 UTC, catalinr commented on src/qt/choice.cpp
> +            wxQtChoice( wxWindow *parent, wxChoice *handler );
```suggestion
            wxQtChoice(wxWindow* parent, wxChoice* handler);
```

2019-01-20 17:37 UTC, catalinr commented on src/qt/choice.cpp
> +    proxyModel->setSourceModel( combo->model() );
```suggestion
    proxyModel->setSourceModel(combo->model());
```

2019-01-20 17:37 UTC, catalinr commented on src/qt/combobox.cpp
> +void wxComboBox::SetActualValue(const wxString &value)
why?
```suggestion
void wxComboBox::SetActualValue(const wxString& value)
```

2019-01-20 17:37 UTC, catalinr commented on src/qt/combobox.cpp
> +        SetStringSelection( value );
why?
```suggestion
        SetStringSelection(value);
```

2019-01-20 18:51 UTC, closed without merging

2019-01-20 23:52 UTC, vadz commented
Just checking: was this closed intentionally?

2019-01-21 09:17 UTC, evileye-uk commented
It was. I'll revisit this when I have the chance, but making our software work takes priority. Any future PRs from me shall conform to the guidelines where differences are to be applied.