Implement label wrapping on wxInfoBar GTK and show it in the sample
wxWidgets/wxWidgets pull request #1443
Opened 2019-07-27 23:43 UTC by oneeyeman1

(Sorry about wasting the PR. I picked the wrong branch and didn't realize).

This implements text wrapping on the wxInfoBar for GTK+ native version. Sample is also updated to easily test the functionality.

I tried to check the generic version, but I guess there is a code that works around this ticket by wrapping the code by explicit \n' character.

I hope someone will be able to fix the generic version and make the label of wxInfoBar wrap.

2019-07-27 23:55 UTC, oneeyeman1 commented
Just adding generic implementation to test proper wrapping.

2019-08-04 19:25 UTC, vadz requested changes
Please fix the GTK version check. TIA!

2019-08-04 19:25 UTC, vadz commented on src/gtk/infobar.cpp
> +    if( gtk_check_version( 2, 10, 0 ) )
You need to add compile-time check too and should use `wx_is_at_least_gtk2()`. Look at any other place where GTK version is checked.

2019-08-04 19:25 UTC, vadz commented on src/generic/infobar.cpp
> +	m_text->Wrap( GetClientSize().GetWidth() );
```suggestion
    m_text->Wrap( GetClientSize().GetWidth() );
```
(removing hard TAB...)

2019-08-04 19:25 UTC, vadz commented on src/gtk/infobar.cpp
> +    gtk_label_set_line_wrap(GTK_LABEL(m_impl->m_label), TRUE );
```suggestion
    gtk_label_set_line_wrap(GTK_LABEL(m_impl->m_label), TRUE);
```
You can use spaces or not, but not use them asymmetrically, this is really too weird.

2019-08-05 00:31 UTC, oneeyeman1 commented
> 
> 
> Please fix the GTK version check. TIA!

All fixed.

Please check and apply.

TIA!

2019-08-05 11:52 UTC, closed without merging