Generate events when programatically selecting a tree item in wxQT
wxWidgets/wxWidgets pull request #1453
Opened 2019-07-30 15:31 UTC by ffa-grahamdawes

The previous implementation of wxTreeCtrl::SelectItem for wxQT update the selection but didn't generate any events.  This minor change corrects this.

2019-08-07 22:19 UTC, oneeyeman1 commented
@ffa-grahamdawes ,
What is the other platforms behavior?
The notion of wx is to not generate events when there is a programmatic change...

2019-08-08 06:50 UTC, ffa-grahamdawes commented
wxMSW and wxGTK generate the events.  These can be seen from the treectrl sample program using "select root" menu item.    Unfortunately, I don't have access to MacOS here and I can't get wx to build on my Mac at home (I'm using a beta version of MacOS + XCode)

2019-09-01 15:29 UTC, catalinr requested changes

2019-09-01 15:29 UTC, catalinr commented on src/qt/treectrl.cpp
> +        const QModelIndex index = indexFromItem(item);
```suggestion
        const QModelIndex &index = indexFromItem(item);
```

2019-09-01 15:29 UTC, catalinr commented on src/qt/treectrl.cpp
> +    if (current != NULL)
```suggestion
    if ( current != NULL )
```
actually this line should not have been changed at all

2019-09-01 15:29 UTC, catalinr commented on src/qt/treectrl.cpp
> +    if (qTreeItem != NULL)
```suggestion
    if ( qTreeItem )
```

2019-09-01 15:29 UTC, catalinr commented on src/qt/treectrl.cpp
> +         m_qtTreeWidget->select(qTreeItem->child(i),  QItemSelectionModel::Select);
```suggestion
        m_qtTreeWidget->select(qTreeItem->child(i), QItemSelectionModel::Select);
```

2019-09-22 00:48 UTC, vadz commented
We actually have this covered by the unit tests in `tests/controls/treectrltest.cpp`, it would be great if wxQt could pass them (but this requires a working `wxUIActionSimulator` and I don't know how well does it work in wxQt -- it seems to be implemented, at least).

Anyhow, thanks for fixing this, merged into #1552 too.

2019-09-27 17:18 UTC, closed without merging