Add GetErrorStr() for obtaining descriptions for wxDynamicLibrary errors
wxWidgets/wxWidgets pull request #22244
Opened 2022-03-29 18:32 UTC by lanurmi

Until now, such error strings were logged, but there was no way to obtain
the string and do something else with it instead of logging.

The purpose of GetErrorStr() this function is similar to that of
wxSysErrorMsg(), but on most platforms dynamic library loading errors
are not available as system errors.

This is a simplified version of the previously rejected PR #1462,
with fewer changes to behavior.

2022-03-29 18:53 UTC, vadz requested changes
Sorry, I've started reviewing this but realized that my actual problem is with the idea of adding non-static `GetErrorStr()` (or whatever it's called) in the first place. `wxDL` is a low-level wrapper for platform-specific functions, so let's just wrap `dlerror()`, i.e. add a static `GetLastError()` returning its result.

This should be a much simpler change but should still be sufficient and would avoid all the questions about the output parameters, `ReportError()` overloads and `wxDL_QUIET` handling.

What do you think?

2022-03-29 18:53 UTC, vadz commented on include/wx/dynlib.h
> +    static bool Unload(wxDllType handle, wxString* errorDest = NULL);
I think we should have either `errorDest` output parameters (which would be normally called `outError` in wx API) _or_ `GetErrorStr()`, but not both.

2022-03-29 18:53 UTC, vadz commented on include/wx/dynlib.h
> +    wxString GetErrorStr() const { return m_lastError; }
If we keep the function, I'd also rename it to either `GetError()` or `GetErrorMessage()`, both of which are already used in the API, while `GetErrorStr()` isn't.

2022-03-29 18:53 UTC, vadz commented on interface/wx/dynlib.h
> +               written to @c errorDest.
```suggestion
               written to @a errorDest (this parameter is only available
               starting from wxWidgets 3.1.6).
```

2022-04-02 21:28 UTC, lanurmi commented
Oh well, while testing my altered implementation with a static `GetLastError()`, I realized that `dlerror()` only returns one error once; i.e. a second call to it will return `NULL` unless a new error has occurred in between. That means in most places with `wxDL`, the `dlerror()`'s return value gets consumed for logging in `ReportError()`, and later when `GetLastError()` calls `dlerror()`, it only gets a `NULL`.

So it can't be done the way proposed after all. Not without disabling `wxDL`'s internal logging.

2022-04-02 21:28 UTC, closed without merging

2022-04-14 21:31 UTC, vadz commented
This is not ideal, but I guess we could still provide `GetLastError()` that could be useful in conjunction with the "raw" functions?