Suppress -Wmaybe_unused warning
wxWidgets/wxWidgets pull request #23167
Opened 2023-01-22 13:25 UTC by Blake-Madden

Under GCC, creating an `std::optional<wxString>` causes a `-Wmaybe_unitialized` warning. Seems like a false positive, but using a default null for `m_str` doesn't hurt and suppresses the warning.

2023-01-25 13:25 UTC, vadz requested changes
Sorry, but I'd rather not apply this in its current state for the reasons explained in the comments.

2023-01-25 13:25 UTC, vadz commented on include/wx/string.h
> +    const wxString *m_str{nullptr};
I'd rather avoid doing this as this gives the impression that this pointer can be null, which is not the case, it must always be valid.

2023-01-25 13:25 UTC, vadz commented on include/wx/string.h
> +    wxStringIteratorNode *m_prev{nullptr}, *m_next{nullptr};
This could be done, but the ctor above should be replaced with `= default` then, it's useless to initialize the members in both places.

2023-01-25 13:25 UTC, vadz commented on include/wx/string.h
> +      size_t m_len{0}; // length, not size, i.e. in chars and without last NUL
Same as above: this is fine to do, but redundant initialization in the ctor should be removed.

2023-01-25 17:26 UTC, Blake-Madden commented
OK, made the suggested changes. Thanks for the feedback.

2023-01-26 19:22 UTC, vadz approved these changes

2023-01-29 00:45 UTC, closed without merging