Support system catch2
wxWidgets/wxWidgets pull request #23654
Opened 2023-06-19 17:40 UTC by Apteryks

Teach the Autoconf/Bakefile build system to use catch2 from the system.

2023-06-19 18:01 UTC, Apteryks commented
> Before looking at it further, this seems to include #23640, right? Does it really need it or could you remove all the other commits except for the last one here?

I wasn't sure, but it seems like it does, at least using Autoconf 2.69.  When attempting to regenerate the configure script with `make -f build/autogen.mk`, I get:
```
[...]
no changes in ../../autoconf_inc.m4
no changes in ../../Makefile.in
0 files modified
make -C build/autoconf_prepend-include

make[1] : on entre dans le répertoire « /home/maxim/src/wxWidgets/build/autoconf_prepend-include »
autom4te -B . --language=Autoconf --freeze --output=autoconf/autoconf.m4f
autoconf/general.m4:301: error: m4_copy: won't overwrite defined macro: AC_PREREQ
autoconf/general.m4:301: the top level
autom4te: /gnu/store/2awzcd1jdd8h65ahdn62ydllrs2s2pk1-m4-1.4.19/bin/m4 failed with exit status: 1
make[1]: *** [Makefile:25 : autoconf/autoconf.m4f] Erreur 1
make[1] : on quitte le répertoire « /home/maxim/src/wxWidgets/build/autoconf_prepend-include »
make: [build/autogen.mk:29 : autoconf_m4f] Erreur 2 (ignorée)
autoconf -B build/autoconf_prepend-include
```

If based on master directly.

2023-06-19 18:18 UTC, vadz commented
Sorry but I simply don't see how is this possible as the last commit doesn't do anything that materially changes anything. You must have some local changes/cached files breaking this.

You should create a PR with just this commit (after fixing the problems in it which result in the CI failures).

2023-06-19 19:57 UTC, Apteryks commented
> Sorry but I simply don't see how is this possible as the last commit doesn't do anything that materially changes anything. You must have some local changes/cached files breaking this.

Maybe it's my version of Autoconf (2.69); there shouldn't be anything cached in my environment:
```
Sorry but I simply don't see how is this possible as the last commit doesn't do anything that materially changes anything. You must have some local changes/cached files breaking this.
```
I'll try cherry picking the single commit I expect to fix this (stop versioning Autoconf-provided M4 files).

2023-08-22 17:31 UTC, vadz requested changes
Thanks for the update but unfortunately there are still some things that could be improved.

I also think that it would make sense to default to built-in version: unlike the other libraries, this is not used for the binaries being distributed, so I don't see any drawbacks to using the built-in version by default and it would avoid warnings about not finding the system one, which would be annoying to see.

2023-08-22 17:31 UTC, vadz commented on build/bakefiles/config.bkl
> +        <option name="WX_TEST_CXXFLAGS"/>
I think it's a bit misleading to call it like this, it should probably be called `CATCH2_CXXFLAGS` or something like this instead.

2023-08-22 17:31 UTC, vadz commented on configure.ac
> +        if test -n "$PKG_CONFIG"; then
We don't test for `PKG_CONFIG` anywhere else, so either we shouldn't do it here neither or we should do it in all the other places too... But is it even possible for it to be empty? I.e. won't configure stop if `PKG_PROG_PKG_CONFIG` doesn't find it?

2023-08-22 17:31 UTC, vadz commented on configure.ac
> +            PKG_CHECK_MODULES([CATCH2], [catch2 < 3],, [
We should use `CATCH2_CFLAGS` somewhere, otherwise compilation will fail if it's not installed under `/usr/include`.

2025-04-30 23:31 UTC, vadz commented
This PR has been in "work needed" state for more than a year and will be closed soon. Please update it, e.g. by commenting here, if anybody intends to resume working on it.

2025-05-10 15:59 UTC, vadz commented
Just FYI, I'll fix and apply it, finally.

2025-05-11 12:06 UTC, Apteryks commented
> Just FYI, I'll fix and apply it, finally.

Thank you.  Sorry for dropping the ball.

2025-05-11 16:54 UTC, closed without merging