Max length on multiple line text control for GTK
wxWidgets/wxWidgets pull request #23928
Opened 2023-10-02 03:18 UTC by oneeyeman1

The text control on Windows supports this, so this PR will bring it in par.

This PR resolves issue 17772.

Only 2 last commits are relevant. Sorry - I thought I was updating master.

Vadim didn't have time back then to finish it. Hopefully he will now. Or Paul.

Hopefully either he or Paul will be able to comment.

What doesn't work here is pasting in the multi-line text control.

I look at implementation, but I'm not sure how to best implement that.

Please review.

I can try to take a look at pasting, but it will take some time..

Thank you.

2023-10-02 17:04 UTC, vadz requested changes
Sorry, there are still several problematic parts here.

2023-10-02 17:04 UTC, vadz commented on src/gtk/textctrl.cpp
> +        // Without following line GTK3 produces warning
Which warning?

2023-10-02 17:04 UTC, vadz commented on src/gtk/textctrl.cpp
> +        gtk_text_buffer_delete( buffer, &offset, &end );
Ideally we should delete just enough to stay under `maxlen` and not all new entry.

2023-10-02 17:04 UTC, vadz commented on src/gtk/textctrl.cpp
> +        return nullptr;
Why is this necessary? We still shouldn't be calling this for multiline controls, it doesn't make sense as they don't have any `GtkEditable`.

It looks like this is a leftover and should be simply reverted.

2023-10-02 17:04 UTC, vadz commented on src/gtk/textentry.cpp
> +        gtk_entry_set_max_length(entry, len);
This should be reverted too.

2023-10-02 19:26 UTC, oneeyeman1 commented on 3rdparty/pcre
@vadz ,
They shouldn't.
As explained in the OP, I thought I was pushing the to master.

2023-10-02 19:29 UTC, oneeyeman1 commented on include/wx/gtk/textentry.h
> +    int GetMaxLength() const { return m_maxlen; }
@vadz,
I probably won't.
I plan to update Mac port with this..

2023-10-05 17:29 UTC, oneeyeman1 commented
@vadz ,
Is there a reason those builds are marked failed even though they are completed without any errors up to wxrc binary?

Thank you.

2023-10-05 17:38 UTC, swt2c commented
> @vadz , Is there a reason those builds are marked failed even though they are completed without any errors up to wxrc binary?
> 
> Thank you.

The errors happened much earlier.  Search the logs for "error:".

2023-10-05 18:00 UTC, oneeyeman1 commented
@swt2c 
> The errors happened much earlier. Search the logs for "error:".,

Thx. I presume they are here because I pushed the Scintilla update.
However they are unrelated.

Is it possible to fix them somehow? I'm not that proficient with Git...

2023-10-05 18:04 UTC, swt2c commented
> @swt2c
> 
> > The errors happened much earlier. Search the logs for "error:".,
> 
> Thx. I presume they are here because I pushed the Scintilla update. However they are unrelated.
> 
> Is it possible to fix them somehow? I'm not that proficient with Git...

It sure looks like they are related to Scintilla.

Yes, it is possible to fix them, but it might be easier for you to create a fresh clone of master and manually re-apply your changes there.

2023-10-05 20:22 UTC, oneeyeman1 commented
@swt2c ,
> > @swt2c
> > > The errors happened much earlier. Search the logs for "error:".,
> > 
> > 
> > Thx. I presume they are here because I pushed the Scintilla update. However they are unrelated.
> > Is it possible to fix them somehow? I'm not that proficient with Git...
> 
> It sure looks like they are related to Scintilla.
> 
> Yes, it is possible to fix them, but it might be easier for you to create a fresh clone of master and manually re-apply your changes there.

Well re-clone will probably be too harsh. ;-)
However I might just sync the master with my fork online, fetch/pull into master and recreate the branch.

This will probably work the same.

2025-02-20 20:54 UTC, closed without merging

2025-02-20 20:55 UTC, oneeyeman1 commented
The later PR was applied so closing...