cmake-build: remove gtk3-dependency from wxbase
wxWidgets/wxWidgets pull request #2434
Opened 2021-07-13 13:39 UTC by jolz

libwx_baseu_3.1.so should not include "-lgtk-3" during link. 
This change has only been tested with linux+gtk2/3 (sorry.)

2021-07-14 11:59 UTC, vadz commented
Thanks for the fix, this seems correct to me, but, as always, I'd appreciate a confirmation from @MaartenBent before merging (TIA!).

2021-07-14 18:06 UTC, MaartenBent requested changes
Maybe we should add similar checks with `if(wxTOOLKIT_INCLUDE_DIRS AND NOT is_base)` and `if(wxTOOLKIT_DEFINITIONS AND NOT is_base)`?

2021-07-15 13:13 UTC, jolz commented on build/cmake/functions.cmake
> +    if(wxTOOLKIT_LIBRARIES AND NOT ${is_base})
Yes, you are right. 
i've just tested it and it works for linux/gtk2 and linux/gtk3.

I'm not sure why we need `-D__WXGTK__`, but <wx/defs.h> requests it (as you said). 

(sorry, this is the first time that i use "pull requests". i hope it stays readable.)

2021-07-15 17:49 UTC, vadz commented
Thanks for the update!

I'm going to merge this soon if there are no objections.

2021-07-26 12:16 UTC, vadz commented
Merged now, thanks!

2021-07-26 12:16 UTC, closed without merging