Fix toast notification always posting the click event on MSW
wxWidgets/wxWidgets pull request #24341
Opened 2024-02-19 10:51 UTC by lanurmi

No idea why this is needed, but would seem to fix #24320.

2024-02-24 22:22 UTC, vadz requested changes
I think the correct thing to do would be to use 3 different handlers, implementing `DesktopToastActivatedEventHandler`, `DesktopToastDismissedEventHandler` and  `DesktopToastFailedEventHandler` respectively instead of a single one.

This should be straightforward to do, AFAICS and we actually only need 2 of them as the third one would do nothing anyhow.

Could you please try to do it like this? TIA!

2024-02-24 22:22 UTC, vadz commented on src/msw/rt/notifmsgrt.cpp
> +        if ( SUCCEEDED(args->QueryInterface(__uuidof(IToastDismissedEventArgs), (void**)&dea)) )
We need to call `Release()` on `dea` in case of success to avoid memory leaks (and the same for `fea` below, of course).

2024-02-26 13:49 UTC, lanurmi commented
> I think the correct thing to do would be to use 3 different handlers, implementing `DesktopToastActivatedEventHandler`, `DesktopToastDismissedEventHandler` and `DesktopToastFailedEventHandler` respectively instead of a single one.

Do you mean doing it [the way it is already done in master](https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/rt/notifmsgrt.cpp#L63-L70)? The thing is that it fails to work correctly, at least not for me. The overload of `Invoke` taking `IInspectable*` always gets called.

Regardless, some unanswered questions are:
* Does the current master do the wrong thing for others besides me?
* Did the current implementation work correctly at the time it was made?
* Is this compiler-specific?

2024-02-29 02:14 UTC, vadz commented
> > I think the correct thing to do would be to use 3 different handlers, implementing `DesktopToastActivatedEventHandler`, `DesktopToastDismissedEventHandler` and `DesktopToastFailedEventHandler` respectively instead of a single one.
> 
> Do you mean doing it [the way it is already done in master](https://github.com/wxWidgets/wxWidgets/blob/master/src/msw/rt/notifmsgrt.cpp#L63-L70)?

No, this code uses a single wxToastEventHandler inheriting from
`Microsoft::WRL::Implements<DesktopToastActivatedEventHandler, DesktopToastDismissedEventHandler, DesktopToastFailedEventHandler>`, while I think we should use 3 (or 2) different wx classes, i.e. `wxToastActivatedEventHandler` and `wxToastDismissedEventHandler`, inheriting/implementing just the single corresponding base class.

> Regardless, some unanswered questions are:
> 
>     * Does the current master do the wrong thing for others besides me?

I didn't test it, but I think it always fails.
 
>     * Did the current implementation work correctly at the time it was made?
> 
>     * Is this compiler-specific?

I don't think so.

2024-09-22 22:28 UTC, vadz commented
Sorry, I should have realized that it was yet another problem with broken COM helpers not supporting multiple interfaces. The real fix is in #24826, please check that it works for you but I'm pretty sure it should.

2024-09-22 22:28 UTC, closed without merging