Fixes to context menus in wxDVC on macOS
wxWidgets/wxWidgets pull request #24697
Opened 2024-07-12 14:26 UTC by vslavik

The primary motivation for this PR was f370e9e8ea5bfbed8a6be0bd4e386ee2a3a4ddfe to fix https://github.com/vslavik/poedit/issues/849, and then I went down the rabbit hole a bit:

1. 37efaacba3dfdfe98520f5a2950ddb75a638b8cd — This is a no-brainer, prevents accidental menu clicks and makes wxOSX consistent with both other ports and native Cocoa context menus. The only question is whether to do it like this or limit oneself to the `wxDefaultPosition` case. I initially did the latter, but this seems more sensible and benefits legacy code that may pass explicit mouse coordinates.

2. f370e9e8ea5bfbed8a6be0bd4e386ee2a3a4ddfe — This fixes the weird behavior when using <kb>control</kbd>-click instead of right-click: there seems to be some corruption of internal state (AppKit, not wx) if `menuForEvent:` doesn't return a menu and we pop one up manually. (When I return a native menu, things behave normally. When I delay `PopupMenu` into next event loop iteration, i.e. after `menuForEvent:` returns, it doesn't help.) This code was there since the very beginning (~2009) and never meaningfully modified, so I don't think there was a particularly deep reason for using `menuForEvent:` [^1]

3. caffdd753a37cecd8be492157e49983a3c6b7f0a — While doing that, I noticed that the mouse position is never used... Apparently, `wxEVT_DATAVIEW_ITEM_CONTEXT_MENU` was always broken and didn't operate on the right-clicked item, but instead used whatever the current selection was. So I fixed that too. 

All of this should be cherry-picked into 3.2 too.

[^1]: In principle, it would be better to use `menuForEvent:` everywhere — see also https://github.com/wxWidgets/wxWidgets/issues/13010#issuecomment-1010846630 — but that would require a new API, e.g. addition of `virtual wxWindow::CreateContextMenu()` to be implementable.

2024-07-12 15:11 UTC, csomor commented
@vslavik thanks a lot, looking forward :-)

2024-07-15 00:14 UTC, vadz requested changes
Thanks! I don't have any comments about this, all the explanations make sense to me.

I believe the original code was written by Hartwig, so I'm cc'ing @hwiesmann in case you have any comments. Otherwise I'll merge (and backport) this soon.

Thanks again!

2024-07-15 07:55 UTC, hwiesmann commented
No comments!

2024-07-15 08:18 UTC, csomor approved these changes
I'm fine with it, added one possible change about the additional `wxDataViewColumn` info, this wasn't there before either in this implementation, but eg in the generic implementation it is filled when this event occurs.

2024-07-15 08:18 UTC, csomor commented on src/osx/dataview_osx.cpp
I don't know about the expectations in the `wxEVT_DATAVIEW_ITEM_CONTEXT_MENU` Handler, but perhaps using the `wxDataViewEvent` constructor that also takes the `wxDataViewColumn` would allow to differentiate on the column as well if wanted?

2024-07-15 16:39 UTC, vslavik commented
> I'm fine with it, added one possible change about the additional wxDataViewColumn info,

Thanks!

That's trivial to do and worth doing. I pushed cd5150f2 that fixes this for both wxOSX and wxGTK.

2024-07-15 17:25 UTC, csomor commented
> > I'm fine with it, added one possible change about the additional wxDataViewColumn info,
> 
> Thanks!
> 
> That's trivial to do and worth doing. I pushed [42ecd8b](https://github.com/wxWidgets/wxWidgets/commit/42ecd8be4274501d3f7b7f14363a185797766b6a) that fixes this for both wxOSX and wxGTK.

perfect, thanks a lot, 

so @vadz please go ahead and merge when it's convenient for you

2024-07-15 21:22 UTC, merged