Explain difference between wxGetTranslation and _() in internat sample
wxWidgets/wxWidgets pull request #25037
Opened 2024-12-31 20:29 UTC by Blake-Madden

Also, more reference to `wxT()` macro in overview topic

2025-01-01 15:33 UTC, vadz requested changes
Sorry, I don't think this is right. The old note was due to the fact that you couldn't use `wxGetTranslation(wxT("foo"))` even if you did pass `-kwxGetTranslation` to `xgettext` and removing `wxT()` from its text means that it loses its meaning.

We should just say that:

1. If you want literal strings inside `wxGetTranslation()` to be translated, you need to use `-kwxGetTranslation`.
2. You shouldn't use `wxT()` inside `wxGetTranslation()`.

2025-01-01 20:30 UTC, PBfordev commented on interface/wx/translation.h
>      @see wxGetTranslation(const wxString&, const wxString&, unsigned, const wxString&)
BTW, this is not linked in [the generated docs](https://docs.wxwidgets.org/latest/group__group__funcmacro__string.html#ga49dcdc17d82a627b7a50d401f1a37d69) and I wonder if this could be fixed by using a correct signature (adding the context argument):
```suggestion
    @see wxGetTranslation(const wxString&, const wxString&, unsigned, const wxString&, const wxString &)
```
[The other override description](https://docs.wxwidgets.org/latest/group__group__funcmacro__string.html#ga3fca2c2319d2481568aef51678e8021e) suffers from the same problem, see the first line.

2025-01-05 17:31 UTC, Blake-Madden commented on interface/wx/translation.h
>      @see wxGetTranslation(const wxString&, const wxString&, unsigned, const wxString&)
Thanks, PB. I saw a few more missing links, so I fixed those too.

2025-01-05 17:32 UTC, Blake-Madden commented
OK, all suggestions applied and fixed a few links also.

2025-01-06 21:11 UTC, vadz commented
Nice, thanks! Will merge in a moment.

2025-01-06 21:16 UTC, closed without merging