wx/xml: Implement line-ending modes for xml saves
wxWidgets/wxWidgets pull request #488
Opened 2017-05-29 14:26 UTC by AdrianDC

* Add 'wxEOL m_mode' to hold the mode
 * Add 'wxString m_eol' to hold the end of lines' string

 * Add SetMode() and SetMode() to set and get the mode
 * Add GetEOL() to get the end of lines' wxString

 * Backwards compatibility preserved by using wxEOL_UNIX

Change-Id: I3e8547b377e2c4060a3a2d97c299a08ea2c0a376
Signed-off-by: Adrian DC <radian.dc@gmail.com>

2017-05-29 14:39 UTC, vadz requested changes
It's unfortunate that we have both `wxEOL` and `wxTextFileType` enums, I don't know which one is more appropriate here, but the advantage of the latter is that we already have the `GetEOL()` method I mentioned, so perhaps it should be used. Alternatively, `wxTextOutputStream` could be refactored to provide a similar method for its enum...

In any case, after settling on the API, could you please update `interface/wx/xml/xml.h` with the new public methods? TIA!

2017-05-29 14:39 UTC, vadz commented on src/xml/xml.cpp
> +    if (m_mode == wxEOL_NATIVE)
Why can't all this code be replaced with `m_eol = wxTextBuffer::GetEol(mode)`?

2017-05-29 14:39 UTC, vadz commented on include/wx/xml/xml.h
> +    const wxString GetEOL() const { return m_eol; }
Sorry, forgot this one: `const` here is superfluous and should be removed.

2017-05-30 12:36 UTC, AdrianDC commented
Thanks for the review.
Improvements done and tested.
Commit message amended.

2017-05-30 17:44 UTC, merged

2017-05-30 17:45 UTC, vadz commented
Merged, thanks!